### PR TITLE
Fix to allow all tunnel types for encapsulating mirrored traffic

### PR DESCRIPTION
**Pull request by jaysheth2**
Removing restrictions to only allow GUE tunnel. Additionally, this PR is tested with GRE tunnel on Vagrant environment.
TODO: Test with other tunnel types as SIT

### CODE REVIEW

**Review by sanfern — CHANGES_REQUESTED** [review]
Can we remove all references of "tunnel-type", its user responsibility to configure any tunnel type. We need to update the docs too.

**Review by sanfern — APPROVED** [review]
LGTM

**Comment by sanfern** [comment]
Can you update the dev env ?

**Review by aka320 — APPROVED** [review]
LGTM

**Pull request merged**
